### PR TITLE
Parse receivers

### PR DESCRIPTION
**Pull request by kovetskiy**
Hi, thanks for the pretty good code, I've added support for parsing method receivers.

Also, I've added new option for all tags - "column" for using column value in vim plugins.

### CODE REVIEW

**Comment by kovetskiy** [comment]
@jstemmer have a look at this please, I use it for more than year, and it works nice

**Comment by jstemmer** [comment]
Hi, thanks for sending a PR!

I've tried this out on the `parser.go` file, which results in a long list of receiver names in the tag list. See the screenshot below. Receiver names are typically very short (most often a single character). A long list of single characters in a random order doesn't seem very useful to me, as you have no idea what particular line this will jump you to. Am I misunderstanding its purpose? Can you describe the problem that this is attempting to solve? 

As for the added column numbers, this sounds like it could be useful. However, the Tagbar plugin for example seems to work well without column information, what are some of the plugins that would benefit from the column numbers?

gotags-pr25

**Comment by kovetskiy** [comment]
Hi, I use it only for highlighting purposes, not for jumps
https://github.com/kovetskiy/synta/blob/master/pythonx/synta/__init__.py#L74

**Comment by jstemmer** [comment]
So if I understand correctly this is mainly to support one plugin in syntax highlighting? It significantly increases the number of tags generated and clutters the tagbar list. I appreciate the work you put into this, but unfortunately I don't think it's a good fit for this project at the moment.

**Pull request closed without merging**
